apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret-envfrom
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      envFrom:
        - secretRef:
            name: my-second-secret
