apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-secret
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      env:
        - name: PASSWORD_ENV_VAR # name of env var
          valueFrom:
            secretKeyRef:
              name: mypassword # name of secret obj
              key: password # name of key in secret obj
